public enum Sector{
    CATEGORY1,
    CATEGORY2,
    CATEGORY3,
    CATEGORY4,
    CATEGORY5,
    CATEGORY6,
    FREE_TURN,
    LOSE_TURN,
    PLAYER_CHOICE,
    OPPONENT_CHOICE,
    SPIN_AGAIN,
    BANKRUPT,
    NONE
}